/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KatalogRouteImport } from './routes/katalog'
import { Route as KeranjangRouteImport } from './routes/keranjang'
import { Route as ProdukIdRouteImport } from './routes/produk.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KatalogRoute = KatalogRouteImport.update({
  id: '/katalog',
  path: '/katalog',
  getParentRoute: () => rootRouteImport,
} as any)
const KeranjangRoute = KeranjangRouteImport.update({
  id: '/keranjang',
  path: '/keranjang',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukIdRoute = ProdukIdRouteImport.update({
  id: '/produk/$id',
  path: '/produk/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/katalog': typeof KatalogRoute
  '/keranjang': typeof KeranjangRoute
  '/produk/$id': typeof ProdukIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/katalog': typeof KatalogRoute
  '/keranjang': typeof KeranjangRoute
  '/produk/$id': typeof ProdukIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/katalog': typeof KatalogRoute
  '/keranjang': typeof KeranjangRoute
  '/produk/$id': typeof ProdukIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/katalog' | '/keranjang' | '/produk/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/katalog' | '/keranjang' | '/produk/$id'
  id: '__root__' | '/' | '/katalog' | '/keranjang' | '/produk/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KatalogRoute: typeof KatalogRoute
  KeranjangRoute: typeof KeranjangRoute
  ProdukIdRoute: typeof ProdukIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katalog': {
      id: '/katalog'
      path: '/katalog'
      fullPath: '/katalog'
      preLoaderRoute: typeof KatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keranjang': {
      id: '/keranjang'
      path: '/keranjang'
      fullPath: '/keranjang'
      preLoaderRoute: typeof KeranjangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/$id': {
      id: '/produk/$id'
      path: '/produk/$id'
      fullPath: '/produk/$id'
      preLoaderRoute: typeof ProdukIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KatalogRoute: KatalogRoute,
  KeranjangRoute: KeranjangRoute,
  ProdukIdRoute: ProdukIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
